name: Run Selenium Tests

on:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:4.21.0-20240709
        ports:
          - 4444:4444

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run pytest in parallel
      run: |
        pytest -m login -n 2 --alluredir=reports/allure-results

    - name: Generate Allure Report
      run: |
        allure generate reports/allure-results -o reports/allure-report --clean

    - name: Upload Allure Report
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: reports/allure-report
